Qazalbash/jaxampler

- README.md
- example/accept_reject_sampler.py
- example/adaptive_accept_reject_sampler.py
- example/inverse_transform_sampler.py
- jaxampler/rvs/crvs/beta.py
- jaxampler/rvs/crvs/boltzmann.py
- jaxampler/rvs/crvs/cauchy.py
- jaxampler/rvs/crvs/chi2.py
- jaxampler/rvs/crvs/crvs.py
- jaxampler/rvs/crvs/exponential.py
- jaxampler/rvs/crvs/gamma.py
- jaxampler/rvs/crvs/logistic.py
- jaxampler/rvs/crvs/lognormal.py
- jaxampler/rvs/crvs/normal.py
- jaxampler/rvs/crvs/pareto.py
- jaxampler/rvs/crvs/rayleigh.py
- jaxampler/rvs/crvs/studentt.py
- jaxampler/rvs/crvs/triangular.py
- jaxampler/rvs/crvs/truncnormal.py
- jaxampler/rvs/crvs/truncpowerlaw.py
- jaxampler/rvs/crvs/uniform.py
- jaxampler/rvs/crvs/weibull.py
- jaxampler/rvs/drvs/binomial.py
- jaxampler/rvs/drvs/drvs.py
- jaxampler/rvs/drvs/geometric.py
- jaxampler/rvs/drvs/poisson.py
- jaxampler/rvs/rvs.py
- jaxampler/sampler/arsampler.py
- jaxampler/sampler/invtranssampler.py
This pull request adds two different functions for numerical calculations in Python: `logpdf_x` and`logpdf_v`. These functions provide flexibility to the user by allowing them to choose the appropriate function based on the type of input and workload distribution.
Fixes #19
> Add point, vectorized, and parallelized numerical functions for Python

- jaxampler/jobj.py
- jaxampler/montecarlo/__init__.py
- jaxampler/montecarlo/integration.py
- jaxampler/montecarlo/montecarlo.py
- jaxampler/rvs/crvs/crvs.py
- jaxampler/rvs/drvs/drvs.py
- jaxampler/rvs/rvs.py
- jaxampler/sampler/sampler.py
This pull request adds the Monte Carlo Integration feature to the project. It includes the necessary code changes to implement the Monte Carlo Box Integration and the required dependencies. This feature allows for numerical integration using the Monte Carlo method. The implementation is based on the JAXampler library. Fixes #17.
> Add Monte Carlo Integration

- jaxampler/_src/rvs/binomial.py
- tests/drvs_test.py
This PR is partially addressing #1
> Unit test for binomial distribution

- jaxampler/_src/rvs/triangular.py
> Incorrect implementation of `rvs.Triangular.logcdf_x`

- tests/crvs_test.py
- tests/drvs_test.py
This PR is partially addressing #1
> Unit tests for Triangular Distribution

- tests/test_truncated_power_law.py
This PR implements the test cases for truncated power law distribution.
> Unit tests for Truncated Power Law Distribution

- tests/pareto_test.py
This PR implements the test cases for pareto distribution.
> Unit tests for Pareto Distribution

- tests/lognormal_test.py
Unit tests for lognormal distribution, partially addressing #1
> unit tests for lognormal distribution

- jaxampler/_src/rvs/boltzmann.py
- tests/boltzmann_test.py
Unit test for Boltzmann distribution partially addressing #1
> Unit test for Boltzmann distribution

- tests/exponential_test.py
Unit tests for exponential distribution addressing #1
> Unit tests for exponential distribution

- .pre-commit-config.yaml
- jaxampler/_src/rvs/weibull.py
- tests/weibull_test.py
This PR contains the unit test for Weibull distribution partially addressing #1
> Unit tests for Weibull distribution

- jaxampler/_src/rvs/beta.py
- pyproject.toml
> Location-Scale variant of Beta distribution

- jaxampler/_src/rvs/cauchy.py
> Loc-Scale variant of Cauchy distribution

- jaxampler/_src/rvs/exponential.py
> Loc-scale variant of Exponential distribution

- jaxampler/_src/rvs/gamma.py
> Loc-scale variant of Gamma distribution

- jaxampler/_src/rvs/geometric.py
> Loc-scale variant of Geometric distribution

- jaxampler/_src/rvs/logistic.py
> Loc-scale variant of Logistic distribution

- jaxampler/_src/rvs/lognormal.py
- jaxampler/_src/rvs/normal.py
- tests/lognormal_test.py
> Loc-scale variant of Normal and LogNormal distribution

- jaxampler/_src/rvs/pareto.py
- tests/pareto_test.py
> Loc-scale variant of Pareto distribution

- jaxampler/_src/rvs/rayleigh.py
- jaxampler/_src/utils.py
> Loc-scale variant of Rayleigh distribution

- jaxampler/_src/rvs/studentt.py
- tests/studentt_test.py
> Loc-scale variant of Student-t distribution

- jaxampler/_src/rvs/truncnormal.py
- jaxampler/_src/utils.py
> Loc-scale variant of Tuncated Normal distribution

- jaxampler/_src/rvs/weibull.py
- tests/weibull_test.py
> Loc-scale variant of Weibull distribution
